name: Build Docker and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t clock-app .

      - name: Create ZIP of project
        run: zip -r clock-artifact.zip . -x "*.git*"

      - name: Upload ZIP to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude ".git/*" --exclude ".github/*"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION}}
          SOURCE_DIR: "./"
